name = "mahjong-scorer-pwa"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB" # Nombre que usaremos en el código (context.env.DB)
database_name = "mahjong_db"
database_id = "8fc1da89-4e93-4201-9de5-f487bc35c08b"
